#!/bin/bash
#### Description: Deploys s3 buckets in your AWS account
#### Written by: Appsecco - cloudsecuritytraining@appsecco.com
#### Modified by: Appsecco - cloudsecuritytraining@appsecco.com


if [ "$EUID" -eq 0 ]
  then echo "Please run as student user!"
  exit
fi

cd /home/student/adef/s3-buckets/
AWS_PROFILE=default ansible-playbook main.yml
