#!/bin/bash
#### Description: Deploys wordpress machine and returns ip
#### Written by: Appsecco - cloudsecuritytraining@appsecco.com
#### Modified by: Appsecco - cloudsecuritytraining@appsecco.com


if [ "$EUID" -eq 0 ]
  then echo "Please run as student user!"
  exit
fi

cd /home/student/adef/wordpress-machine/terraform
terraform init
terraform plan -out wordpress-machine.plan -var uniquename=$bapname
terraform apply wordpress-machine.plan
